pathfinder:
  enabled: false

robot:
  start:
    x: 475 # width 290 / 2 + 330 offset start
    y: 225 # width 360 + 90 to fill zone
    angle: 0

actions:
  main: "homolog"
  timeout: 10 # in seconds
  move_only_forward: false
  
simulation: # 1 for Up, 0 for Down
  side: 0

interface:
  can_interface:
    device: "can1"