pathfinder:
  enabled: false

robot:
  start:
    x: 475 # width 290 / 2 + 330 offset start
    y: 225 # width 360 + 90 to fill zone
    angle: 0

actions:
  main: "moving_only_2"
  timeout: 96 # in seconds

sonars:
  back_trigger_distance: 25 # cm
  front_trigger_distance: 25 # cm

  escape_distance: 200 # mm

  proximity_timeout: 3 # seconds before giving up on wait for obstacle to leave
  
simulation: # 1 for Up, 0 for Down
  side: 0

interface:
  can_interface:
    device: "can1"