pathfinder:
  enabled: false

robot:
  start:
    x: 520
    y: 225 # width 360 + 90 to fill zone
    angle: 0

actions:
  main: "main"
  timeout: 100 # in seconds
  move_only_forward: true
  
simulation: # 1 for Up, 0 for Down
  side: 0

interface:
  can_interface:
    device: "can1"