<?xml version="1.0"?>
<robot name="beagle_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<property name="PI" value="3.1415926535897931"/>

	<property name="robotWidth" value="0.28"/>
	<property name="robotLength" value="0.27"/>
	<property name="robotHeight" value="0.35"/>

	<property name="wheelRadius" value="0.03"/>
	<property name="wheelLength" value="0.01"/>

	<xacro:include filename="$(find robot_description)/urdf/materials.xacro" />

	<link name="base_link">
		<visual>
			<geometry>
				<box size="${robotWidth} ${robotLength} ${robotHeight}"/>
			</geometry>
			<material name="green"/>
		</visual>
	</link>

	<link name="left_wheel">
		<visual>
			<geometry>
				<cylinder radius="${wheelRadius}" length="${wheelLength}"/>
			</geometry>
			<material name="blue"/>
		</visual>
	</link>

	<link name="right_wheel">
		<visual>
			<geometry>
				<cylinder radius="${wheelRadius}" length="${wheelLength}"/>
			</geometry>
			<material name="red"/>
		</visual>
	</link>

	<joint name="base_link_right_wheel" type="continuous">
		<origin xyz="0.1 0.0 ${-robotHeight/2}" rpy="0.0 ${PI/2} 0.0"/>
		<parent link="base_link"/>
		<child link="right_wheel"/>
		<axis xyz="0.0 0.0 1.0"/>
	</joint>

	<joint name="base_link_left_wheel" type="continuous">
		<origin xyz="-0.1 0.0 ${-robotHeight/2}" rpy="0.0 ${PI/2} 0.0"/>
		<parent link="base_link"/>
		<child link="left_wheel"/>
		<axis xyz="0.0 0.0 1.0"/>
	</joint>
</robot>